### PR TITLE
New review of byte-compile warnings

### PR DESCRIPTION
**Pull request by sergiruiztrepat**
Hi @tecosaur,

Here is my second review of byte-compile warnings.

### CODE REVIEW

**Comment by tecosaur** [comment]
Thanks for this! I'd not a fan of the code duplication though. I just stumbled across an example of someone using `eval-when-compile` to have the macros defining variables be expanded for compilation. I'm going to push a commit trying that and hope that it does the trick :crossed_fingers:.

**Comment by tecosaur** [comment]
Hmmm. Unfortunately it seems `eval-when-compile` tries to execute the expanded macro results too which I think causes the error seen in the CI for the last commit. The idea of this approach (expand macros at compile) does seem nicer to me — if it can be made to work. Might you have any ideas?

**Comment by sergiruiztrepat** [comment]
Hi! At the moment I don't know how to solve it, but I will investigate...

**Comment by tecosaur** [comment]
Please let me know if you have any ideas. Regarding wrapped lines, I'm talking about the effect of `visual-line-mode` which can cause a long line of text to be split onto another line - and so another line is needed in the screenshot frame but the line count is unchanged. Does that make sense?

**Comment by sergiruiztrepat** [comment]
Hi @tecosaur ,

I have tried several things in order to avoid byte-compile warnings, but they didn't work without code duplication. I am sorry.

About wrapped lines, I understand, I will have a look (depending on time), but you can close this issue if you want.

Thanks!

**Comment by tecosaur** [comment]
No need to be sorry, I really appreciate you spending time trying to help out with this.

Glad to hear you're willing to investigate the wrapped lines issue :slightly_smiling_face:.

**Comment by tecosaur** [comment]
This should be resolved in e7a8941d9ff2274c7f784c4d89c2ed4a70a45b0a now.

**Pull request closed without merging**
