### PR TITLE
Add custom variables for screenshot parameters

### PR DESCRIPTION
**Pull request by KaratasFurkan**
Hi, nice package, thank you!

I wanted to change some default parameters but they was hardcoded, so I create custom variables for all of them.

### CODE REVIEW

**Comment by tecosaur** [comment]
Hi! Thanks for the PR. These variables are all actually defined in macros :slightly_smiling_face:

I'm not a fan of hardcoding either. I don't think I've made this clear in the docs though, I'll address this at some point.

**Comment by KaratasFurkan** [comment]
I didn't get the point, do you mean you dynamically created these variables? my changes are pointless?

I realized that my fork is not up to date btw, I will rebase it if you are going to merge this.

**Comment by tecosaur** [comment]
If you see the macro `screenshot--define-infix` you'll see it expands to include a `defcustom`.

**Comment by KaratasFurkan** [comment]
Ahh, I see, I feel bad now :(

😄 Lets close this PR.

**Comment by tecosaur** [comment]
NP, thanks for creating a PR when you saw a problem, even if Hat problem wasn't really a problem :slightly_smiling_face:.

**Pull request closed without merging**
